export const players = [
	{
		name: 'Novak Djokovic',
		firstName: 'Novak',
		lastName: 'Djokovic',
		image: 'djokovic_full_ao19.png',
		country: 'Serbia',
		countryimage: 'srb.svg',
		age: 34,
		birthdate: '22 May 1987',
		birthplace: 'Belgrade, Serbia"',
		plays: 'Right-Handed, Two Handed Backhand',
		rank: 1,
		points: 11015,
		socialmedia: [
			{ facebook: 'djokovicofficial' },
			{ twitter: 'DjokerNole' },
			{ instagram: 'djokernole' },
			{ youtube: 'djokovicofficial' },
			{ web: 'http://novakdjokovic.com' },
			{ topcourt: null },
		],
		weight: 77,
		height: 188,
		coach: ['Goran Ivanisevic', 'Marian Vajda'],
		turnedpro: 2003,
	},
	{
		name: 'Daniil Medvedev',
		firstName: 'Daniil',
		lastName: 'Medvedev',
		image: 'medvedev_full_ao20.png',
		country: 'Russia',
		countryimage: 'rus.svg',
		age: 25,
		birthdate: '1996.02.11',
		birthplace: 'Belgrade, Serbia"',
		plays: 'Right-Handed, Two Handed Backhand',
		rank: 2,
		points: 8935,
		socialmedia: [
			{ facebook: null },
			{ twitter: 'DaniilMedwed' },
			{ instagram: 'medwed33' },
			{ youtube: null },
			{ web: null },
			{ topcourt: null },
		],
		weight: 83,
		height: 198,
		coach: ['Gilles Cervara'],
		turnedpro: 2014,
	},
	{
		name: 'Alexander Zverev',
		firstName: 'Alexander',
		lastName: 'Zverev',
		image: 'zverev_full_ao20.png',
		country: 'Germany',
		countryimage: 'ger.svg',
		age: 24,
		birthdate: '1997.04.20',
		birthplace: 'Belgrade, Serbia"',
		plays: 'Right-Handed, Two Handed Backhand',
		rank: 3,
		points: 7970,
		socialmedia: [
			{ facebook: 'alexzverev12345' },
			{ twitter: 'AlexZverev' },
			{ instagram: 'alexzverev123' },
			{ youtube: null },
			{ web: null },
			{ topcourt: 'alexander-zverev' },
		],
		weight: 90,
		height: 198,
		coach: ['Alexander Zverev Sr.'],
		turnedpro: 2013,
	},
	{
		name: 'Stefanos Tsitsipas',
		firstName: 'Stefanos',
		lastName: 'Tsitsipas',
		image: 'tsitsipas_full_ao20.png',
		country: 'Greece',
		countryimage: 'gre.svg',
		age: 23,
		birthdate: '1998.08.12',
		birthplace: 'Belgrade, Serbia"',
		plays: 'Right-Handed, Two Handed Backhand',
		rank: 4,
		points: 6540,
		socialmedia: [
			{ facebook: 'StefTsitsipas' },
			{ twitter: 'StefTsitsipas' },
			{ instagram: 'stefanostsitsipas98' },
			{ youtube: 'channel/UCO5HFpRQMOBZvFoHgOneaMQ' },
			{ web: 'http://www.stsitsipas.com' },
			{ topcourt: null },
		],
		weight: 90,
		height: 193,
		coach: ['Apostolos Tsitsipas'],
		turnedpro: 2016,
	},
	{
		name: 'Rafael Nadal',
		firstName: 'Rafael',
		lastName: 'Nadal',
		image: 'nadal_full_ao20.png',
		country: 'Spain',
		countryimage: 'esp.svg',
		age: 35,
		birthdate: '1986.06.03',
		birthplace: 'Belgrade, Serbia"',
		plays: 'Right-Handed, Two Handed Backhand',
		rank: 5,
		points: 4875,
		socialmedia: [
			{ facebook: 'Nadal' },
			{ twitter: 'RafaelNadal' },
			{ instagram: 'rafaelnadal' },
			{ youtube: null },
			{ web: 'http://www.rafaelnadal.com' },
			{ topcourt: null },
		],
		weight: 85,
		height: 185,
		coach: ['Carlos Moya', 'Francisco Roig', 'Marc Lopez'],
		turnedpro: 2001,
	},
	{
		name: 'Andrey Rublev',
		firstName: 'Andrey',
		lastName: 'Rublev',
		image: 'rublev_full_ao20.png',
		country: 'Russia',
		countryimage: 'rus.svg',
		age: 24,
		birthdate: '1997.10.20',
		birthplace: 'Belgrade, Serbia"',
		plays: 'Right-Handed, Two Handed Backhand',
		rank: 6,
		points: 4785,
		socialmedia: [
			{ facebook: null },
			{ twitter: 'AndreyRublev97' },
			{ instagram: 'andreyrublev' },
			{ youtube: null },
			{ web: 'https://andrey-rublev.com' },
			{ topcourt: 'andrey-rublev' },
		],
		weight: 75,
		height: 188,
		coach: ['Fernando Vicente'],
		turnedpro: 2014,
	},
	{
		name: 'Matteo Berrettini',
		firstName: 'Matteo',
		lastName: 'Berrettini',
		image: 'berrettini_full_2022_hb1.png',
		country: null,
		countryimage: 'ita.svg',
		age: 25,
		birthdate: '1996.04.12',
		birthplace: 'Belgrade, Serbia"',
		plays: 'Right-Handed, Two Handed Backhand',
		rank: 7,
		points: 4568,
		socialmedia: [
			{ facebook: null },
			{ twitter: null },
			{ instagram: 'matberrettini' },
			{ youtube: null },
			{ web: null },
			{ topcourt: null },
		],
		weight: 95,
		height: 196,
		coach: ['Vincenzo Santopadre', 'Marco Gulisano', 'Umberto Rianna'],
		turnedpro: 2015,
	},
	{
		name: 'Casper Ruud',
		firstName: 'Casper',
		lastName: 'Ruud',
		image: 'ruud_full_ao20.png',
		country: 'Norway',
		countryimage: 'nor.svg',
		age: 23,
		birthdate: '1998.12.22',
		birthplace: 'Belgrade, Serbia"',
		plays: 'Right-Handed, Two Handed Backhand',
		rank: 8,
		points: 4155,
		socialmedia: [
			{ facebook: 'CasperRuudTennis' },
			{ twitter: 'casperruud98' },
			{ instagram: 'casperruud' },
			{ youtube: 'casper-ruud' },
			{ web: 'https://www.casper-ruud.com' },
			{ topcourt: 'casper-ruud' },
		],
		weight: 77,
		height: 183,
		coach: ['Christian Ruud'],
		turnedpro: 2015,
	},
	{
		name: 'Felix Auger-Aliassime',
		firstName: 'Felix',
		lastName: 'Auger-Aliassime',
		image: 'auger_aliassime_full_nov_2021.png',
		country: 'Canada',
		countryimage: 'can.svg',
		age: 21,
		birthdate: '2000.08.08',
		birthplace: 'Belgrade, Serbia"',
		plays: 'Right-Handed, Two Handed Backhand',
		rank: 9,
		points: 3608,
		socialmedia: [
			{ facebook: null },
			{ twitter: 'felixtennis' },
			{ instagram: 'felixaliassime' },
			{ youtube: null },
			{ web: null },
			{ topcourt: 'felix-auger-aliassime' },
		],
		weight: 88,
		height: 193,
		coach: ['Frederic Fontang', 'Toni Nadal'],
		turnedpro: 2017,
	},
	{
		name: 'Jannik Sinner',
		firstName: 'Jannik',
		lastName: 'Sinner',
		image: 'sinner_full_nov_2021.png',
		country: 'Italy',
		countryimage: 'ita.svg',
		age: 20,
		birthdate: '2001.08.16',
		birthplace: 'Belgrade, Serbia"',
		plays: 'Right-Handed, Two Handed Backhand',
		rank: 10,
		points: 3390,
		socialmedia: [
			{ facebook: null },
			{ twitter: 'janniksin' },
			{ instagram: 'janniksin' },
			{ youtube: null },
			{ web: null },
			{ topcourt: null },
		],
		weight: 76,
		height: 188,
		coach: ['Riccardo Piatti', 'Andrea Volpini'],
		turnedpro: 2018,
	},
	{
		name: 'Akira Santillan',
		firstName: 'Akira',
		lastName: 'Santillan',
		image: 'santillan_full_ao18.png',
		country: 'Australia',
		countryimage: 'aus.svg',
		age: 24,
		birthdate: '1997.05.22',
		birthplace: 'Belgrade, Serbia"',
		plays: 'Right-Handed, Two Handed Backhand',
		rank: 328,
		points: 151,
		socialmedia: [
			{ facebook: null },
			{ twitter: null },
			{ instagram: 'akirasantillan' },
			{ youtube: null },
			{ web: null },
			{ topcourt: null },
		],
		weight: 78,
		height: 180,
		coach: ['Dean Santillan'],
		turnedpro: 2013,
	},
];
